version: "3"
services:
  springboot-app:
    container_name: springboot-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    networks:
      - backend-network      
      - frontend-network
      - db-network
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: finalproject
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qkqh1234!
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ~/mysql_database/:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: finalproject
      MYSQL_ROOT_PASSWORD: qkqh1234!
    networks:
      - backend-network
      - db-network
  react-app:
    container_name: react-app
    build: ../front/.
    networks:
      - frontend-network
    ports:
      - 3000:3000
    restart: always

networks:
  backend-network:
  frontend-network:
  db-network:
